#!/usr/bin/env bash
# Write a Bash script that displays numbers from 1 to 100.
#	* Displays FizzBuzz when the number is a multiple of 3 and 5
#	* Displays Fizz when the number is multiple of 3
#	* Displays Buzz when the number is a multiple of 5
#	* Otherwise, displays the number
#	* In a list format

i=1
while [[ "$i" -le 100 ]]
do
	if [[ $(( i % 15 )) = 0 ]]
	then
		echo "FizzBuzz"
		i=$(( i + 1 ))

	elif [[ $(( i % 3 )) = 0 ]]
	then
		echo "Fizz"
                i=$(( i + 1 ))

	elif [[ $(( i % 5 )) = 0 ]]
	then
		echo "Buzz"
                i=$(( i + 1 ))

	else
		echo "$i"
		i=$(( i + 1 ))
	fi
done
