#!/usr/bin/env bash
#Write a Bash script that displays numbers from 1 to 20 and:
#	* displays 4 and then bad luck from China for the 4th loop iteration
#	* displays 9 and then bad luck from Japan for the 9th loop iteration
#	* displays 17 and then bad luck from Italy for the 17th loop iteration

i=1
while [[ $i -le 20 ]]
do
	case $i in
		4)	echo -e "$i\nbad luck from China"
			i=$(( i + 1 ))
			;;
		9) 	echo -e "$i\nbad luck from Japan"
			i=$(( i + 1 ))
			;;
		17)	echo -e "$i\ngood luck from Italy"
			i=$(( i + 1 ))
			;;
		*)	echo "$i"
			i=$(( i + 1 ))
	esac
done
